            - 名称：上传构建产物
  使用：actions/upload-artifact@v5.0.0
  和：
    # 工件名称
    名称：# 可选，默认为 artifact
    # 用于描述要上传内容的文件、目录或通配符模式
    小路：
    # 如果使用提供的路径找不到文件，则应执行此操作。
可选方案：
  警告：输出警告，但不使操作失败。
  错误：操作失败并显示错误消息
  忽略：不输出任何警告或错误，操作不会失败。

    if-no-files-found: # 可选，默认值为 warn
    # 工件过期时间（以天为单位）。0 表示使用默认保留期限。
最短 1 天，最长 90 天，除非在存储库设置页面中更改。

    保留天数：# 可选
    # Zlib 对工件归档文件应用的压缩级别。取值范围为 0 到 9：- 0：不压缩 - 1：最佳速度 - 6：默认压缩（与 GNU Gzip 相同） - 9：最佳压缩。级别越高，压缩效果越好，但上传时间越长。对于不易压缩的大文件，建议使用 0 以显著加快上传速度。

    压缩级别：# 可选，默认值为 6
    # 如果为真，则会在上传新工件之前删除同名工件。如果为假，则当同名工件已存在时，操作将失败。如果工件不存在，则不会失败。

    覆盖：# 可选，默认为 false
    # 如果为真，则隐藏文件将包含在工件中。如果为假，则隐藏文件将从工件中排除。

    include-hidden-files: # 可选，默认为 false
          
